#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += leh800b_mcbcpld.o
leh800b_mcbcpld-objs := leh800b/leh800b_mcbcpld_i2c.o lib/regbit-sysfs.o
